In [8]:
import numpy as np
a = np.arange(6)
print(a, np.sort(a), a.mean())
b = np.arange(12).reshape(4, 3)
print(b)
print(b.sum(axis = 0))
print(b.ravel())
print(b.flatten())
print(b)

[0 1 2 3 4 5] [0 1 2 3 4 5] 2.5
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[18 22 26]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [11]:
b = np.arange(12).reshape(3, 4).transpose()
b

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [12]:
print(np.searchsorted(
    [1, 2, 3, 4, 5],
    [-10, 10, 3, 5]
))

[0 5 2 4]


In [14]:
a = np.array([0,3,5,3,7,6,13,2,8])

print(a.sum())
print(np.sum(a))
print(sum(a)) 

47
47
47


In [20]:
import random
b = np.random.randint(100, size=25)

In [21]:
b / np.std(b)

array([1.94026813, 3.40462144, 2.85548895, 0.07321767, 2.81888011,
       3.11175077, 2.63583595, 1.72061513, 1.17148264, 1.5741798 ,
       0.80539432, 2.81888011, 2.89209778, 3.03853311, 1.9036593 ,
       2.59922712, 1.31791798, 1.46435331, 0.        , 1.46435331,
       3.18496844, 3.62427443, 1.50096214, 1.13487381, 3.03853311])

In [86]:
b = np.random.randint(100, size=10)
print(b)
print(max(b))
print(np.searchsorted(b, max(b)))

[54  1 29 99 15 71  3 84 14  1]
99
10
